### ISSUE TITLE
[Cleanup] Merge azure charts to a single branch

### ISSUE THREAD

**Issue by ismail-shahzad** [datopian/dx-helm-ckan#15]
Currently we have 4 branches for Azure compatible CKAN charts 
* https://github.com/datopian/dx-helm-ckan/tree/enable_ghost
* https://github.com/datopian/dx-helm-ckan/tree/fcsc/k8s_v1.25
* https://github.com/datopian/dx-helm-ckan/tree/azure-deployment
* https://github.com/datopian/dx-helm-ckan/tree/azure_hasura_datapi

We need to merge them all into one, preferrably `azure-deployment` and remove redundant branches.

## Acceptance Criteria

* [ ] All the branches for azure deployment have been merged without any conflicts
* [ ] Redundant branches have been deleted

## Tasks

* [ ] Raise a PR
* [ ] Resolve conflicts if any
* [ ] Delete redundant branches
